import React , {useState} from 'react';
import {useNavigate} from "react-router-dom";
import {preview} from "../assets"
import { getRandomPrompt } from '../utils';
import { FormField , Loader } from '../components';

export default function CreatePost() {

  const navigate = useNavigate();
  const [form , SetForm] = useState({
    name :"",
    prompt:"",
    photo:""
  })
  const [generatingImg , setGeneratingImg] = useState(false);
  const [loading , setLoading] = useState(false)

  const handleSubmit = ()=>{

  }
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
      <h1 className='font-extrabold text-[#222328] text-[32px]'>Create</h1>
            <p className='mt-2 text-[#66e75] text-[16px] max-w[5000px]'>Create imaginative and visually stunning images generated by Ai </p>
      </div>
      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>

        </div>
      </form>
    </section>
  )
}



// 41:56
